const fs = require('fs')

const lines = ['/* File was autogenerated using client/repack.js */']
const loadStatic = s => JSON.parse(fs.readFileSync('../server/static/'+s))
const toSassMap = obj => JSON.stringify(obj, null, 2)
      .replace(/[\{]/g,"(")
      .replace(/[\}]/g,")")

const link_colors = loadStatic('sm/link_colors.json')
const templates = loadStatic('sm/icons/template_sprites.json')
lines.push(`$link_colors: ${toSassMap(link_colors)};`)
lines.push(`$template_sprites: ${toSassMap(templates)};`)

const icons = loadStatic('sm/icons.json')
const icon_categories = ['items', 'ui_items', 'custom-items', 'block', 'block-alt']
icon_categories.forEach((category) => {
  lines.push(`$${category}: ${icons[category]['icons'].join(' ')};`)
})

fs.writeFileSync('./src/css/variables.scss', lines.join('\n\n'))
