const fs = require('fs')

const lines = ['/* File was autogenerated using client/repack.js */']
const loadStatic = s => JSON.parse(fs.readFileSync('../server/static/'+s))
const toSassMap = obj => JSON.stringify(obj, null, 2)
      .replace(/[\{]/g,"(")
      .replace(/[\}]/g,")")

const portal_colors = loadStatic('sm/portal/colors.json')
const templates = loadStatic('sm/icons/template_sprites.json')
lines.push(`$portal_colors: ${toSassMap(portal_colors)};`)
lines.push(`$template_sprites: ${toSassMap(templates)};`)

const icons = loadStatic('sm/icons.json')
lines.push(`$ui_items: ${icons['ui_items']['icons'].join(' ')};`)

fs.writeFileSync('./src/css/variables.scss', lines.join('\n\n'))
