# Generated by Django 4.0.5 on 2023-11-13 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracker',
            name='racetime_url',
        ),
        migrations.AddField(
            model_name='tracker',
            name='active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
