# Generated by Django 4.0.5 on 2022-06-11 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatchedSprite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hashed_sprites')),
                ('datahash', models.CharField(max_length=32)),
                ('data', models.JSONField(default=dict)),
                ('type', models.CharField(blank=True, default='', max_length=32)),
                ('modifier', models.CharField(blank=True, choices=[('standing', 'standing'), ('walking', 'walking'), ('wall', 'wall'), ('inblock', 'inblock'), ('inegg', 'inegg'), ('respawn', 'respawn'), ('up', 'up'), ('down', 'down'), ('left', 'left'), ('right', 'right')], max_length=16, null=True)),
                ('color', models.CharField(blank=True, choices=[('black', 'black'), ('blue', 'blue'), ('dust', 'dust'), ('eye', 'eye'), ('gold', 'gold'), ('gray', 'gray'), ('green', 'green'), ('mixed', 'mixed'), ('orange', 'orange'), ('pink', 'pink'), ('purple', 'purple'), ('red', 'red'), ('white', 'white')], max_length=16, null=True)),
                ('category', models.CharField(blank=True, choices=[('block', 'block'), ('geo', 'geo'), ('hex', 'hex'), ('item', 'item'), ('enemy', 'enemy'), ('obstacle', 'obstacle'), ('door', 'door'), ('station', 'station'), ('animation', 'animation'), ('trash', 'trash')], max_length=16, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlmSprite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hashed_sprites')),
                ('datahash', models.CharField(max_length=32)),
                ('data', models.JSONField(default=dict)),
                ('layer', models.CharField(choices=[('bts', 'bts'), ('plm', 'plm'), ('tile', 'tile'), ('unknown', 'unknown')], default='unknown', max_length=16)),
                ('approved', models.BooleanField(default=False)),
                ('match_method', models.CharField(blank=True, choices=[('manual', 'manual'), ('automatch', 'automatch'), ('creation', 'creation')], default='', max_length=16)),
                ('extra_xy', models.JSONField(blank=True, default=list)),
                ('extra_plmsprite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sprite.plmsprite')),
                ('matchedsprite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sprite.matchedsprite')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
