# Generated by Django 4.0.5 on 2022-06-12 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sprite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plmsprite',
            name='extra_plmsprite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sprite.plmsprite'),
        ),
    ]
