# Generated by Django 4.0.5 on 2022-06-07 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plmsprite',
            name='match_xy',
            field=models.JSONField(default=list),
        ),
    ]
