# Generated by Django 4.0.5 on 2022-06-13 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sprite', '0002_alter_plmsprite_extra_plmsprite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchedsprite',
            name='category',
            field=models.CharField(blank=True, choices=[('block', 'block'), ('geo', 'geo'), ('hex', 'hex'), ('item', 'item'), ('enemy', 'enemy'), ('obstacle', 'obstacle'), ('door', 'door'), ('station', 'station'), ('animation', 'animation'), ('trash', 'trash'), ('_wings', '_wings'), ('_parts', '_parts')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='plmsprite',
            name='matchedsprite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sprite.matchedsprite'),
        ),
    ]
