# Generated by Django 4.0.5 on 2022-06-13 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maptroid', '0022_smilesprite_template'),
        ('sprite', '0003_alter_matchedsprite_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomPlmSprite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xy', models.JSONField()),
                ('plmsprite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sprite.plmsprite')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maptroid.room')),
            ],
        ),
    ]
