# Generated by Django 4.0.5 on 2022-06-10 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sprite', '0003_remove_matchedsprite_primary_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plmsprite',
            name='match_xy',
        ),
        migrations.AlterField(
            model_name='plmsprite',
            name='matchedsprite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sprite.matchedsprite'),
        ),
    ]
