# Generated by Django 4.0.5 on 2022-11-07 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maptroid', '0025_alter_world_options_video_is_full_playthrough_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(choices=[('noob', 'noob'), ('beginner', 'beginner'), ('intermediate', 'intermediate'), ('advanced', 'advanced'), ('master', 'master')], max_length=16)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('rooms', models.ManyToManyField(to='maptroid.room')),
            ],
        ),
        migrations.CreateModel(
            name='UserSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(blank=True, default=dict)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skill.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SkillVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.IntegerField(blank=True, null=True)),
                ('end_time', models.IntegerField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skill.skill')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maptroid.video')),
            ],
        ),
        migrations.CreateModel(
            name='SkillResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='skill_resources')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skill.skill')),
            ],
        ),
        migrations.AddField(
            model_name='skill',
            name='videos',
            field=models.ManyToManyField(through='skill.SkillVideo', to='maptroid.video'),
        ),
    ]
