# Generated by Django 4.0.5 on 2022-11-07 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0002_remove_userskill_data_userskill_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userskill',
            name='note',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
