# Generated by Django 3.2.7 on 2021-11-13 23:44

from django.db import migrations, models
import django.db.models.deletion
import maptroid.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(blank=True, default='', max_length=1)),
                ('image', models.ImageField(upload_to='smile_characters')),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='World',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('slug', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('slug', models.CharField(max_length=128)),
                ('data', models.JSONField(blank=True, default=maptroid.models.default_data)),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maptroid.world')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('title', models.CharField(max_length=255)),
                ('channel_name', models.CharField(max_length=30)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maptroid.world')),
            ],
        ),
        migrations.CreateModel(
            name='Sprite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layers', models.JSONField(default=list)),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('dhash', models.CharField(max_length=24)),
                ('image', models.ImageField(upload_to='smile_sprites')),
                ('type', models.CharField(choices=[('item', 'item'), ('map', 'map'), ('unknown', 'unknown')], default='unknown', max_length=16)),
                ('worlds', models.ManyToManyField(to='maptroid.World')),
            ],
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.ImageField(upload_to='screenshots')),
                ('output', models.ImageField(blank=True, null=True, upload_to='output')),
                ('data', models.JSONField(blank=True, default=dict)),
                ('world', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maptroid.world')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maptroid.zone')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('key', models.CharField(blank=True, max_length=128, null=True)),
                ('sprite_ids', models.JSONField(default=list)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('world', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maptroid.world')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maptroid.zone')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(blank=True, default=dict)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maptroid.room')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maptroid.zone')),
            ],
        ),
    ]
