# Generated by Django 3.2.7 on 2021-09-27 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maptroid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='sprite_ids',
            field=models.JSONField(default=list),
        ),
        migrations.CreateModel(
            name='Sprite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layers', models.JSONField(default=list)),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('dhash', models.CharField(max_length=24)),
                ('image', models.ImageField(upload_to='smile_sprites')),
                ('type', models.CharField(choices=[('item', 'item'), ('map', 'map'), ('unknown', 'unknown')], default='unknown', max_length=16)),
                ('worlds', models.ManyToManyField(to='maptroid.World')),
            ],
        ),
    ]
