# Generated by Django 3.2.7 on 2021-11-16 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maptroid', '0002_auto_20211116_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='name',
            field=models.CharField(default='arst', max_length=64),
            preserve_default=False,
        ),
    ]
