# Generated by Django 3.2.7 on 2021-10-17 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maptroid', '0003_auto_20211017_1026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='screenshot',
            old_name='image',
            new_name='src',
        ),
    ]
