# Generated by Django 3.2.7 on 2021-10-19 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maptroid', '0004_rename_image_screenshot_src'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='room',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maptroid.zone'),
        ),
    ]
