# Generated by Django 3.2.7 on 2021-11-16 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maptroid', '0004_video_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='name',
            new_name='label',
        ),
    ]
