# Generated by Django 3.2.7 on 2021-10-20 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maptroid', '0005_auto_20211019_0242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='screenshot',
            old_name='src',
            new_name='original',
        ),
    ]
