# Generated by Django 3.2.7 on 2021-10-20 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maptroid', '0006_rename_src_screenshot_original'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenshot',
            name='output',
            field=models.ImageField(blank=True, null=True, upload_to='output'),
        ),
    ]
