# Generated by Django 3.2.7 on 2021-11-25 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maptroid', '0007_auto_20211125_0310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smilesprite',
            name='color_sum',
        ),
        migrations.AddField(
            model_name='smilesprite',
            name='average_color',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
