# Generated by Django 3.2.7 on 2021-10-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maptroid', '0007_screenshot_output'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
