# Generated by Django 3.2.7 on 2021-11-02 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maptroid', '0008_zone_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zone',
            options={'ordering': ('name',)},
        ),
        migrations.RemoveField(
            model_name='world',
            name='zones',
        ),
        migrations.AddField(
            model_name='zone',
            name='world',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='maptroid.world'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='zone',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
