# Generated by Django 3.2.7 on 2021-11-25 12:46

from django.db import migrations
import maptroid.models


class Migration(migrations.Migration):

    dependencies = [
        ('maptroid', '0008_auto_20211125_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smilesprite',
            name='dhash',
            field=maptroid.models.ImageHashField(),
        ),
    ]
