# Generated by Django 3.2.7 on 2021-11-25 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maptroid', '0009_alter_smilesprite_dhash'),
    ]

    operations = [
        migrations.AddField(
            model_name='smilesprite',
            name='main_color',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
