# Generated by Django 3.2.7 on 2021-11-07 14:05

from django.db import migrations, models
import django.db.models.deletion
import maptroid.models


class Migration(migrations.Migration):

    dependencies = [
        ('maptroid', '0009_auto_20211102_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='data',
            field=models.JSONField(blank=True, default=maptroid.models.default_data),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(blank=True, default=dict)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maptroid.room')),
            ],
        ),
    ]
