# Generated by Django 3.2.7 on 2021-11-26 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maptroid', '0010_smilesprite_main_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='smilesprite',
            name='size',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
