# Generated by Django 3.2.7 on 2021-11-26 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maptroid', '0011_smilesprite_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smilesprite',
            name='average_color',
        ),
        migrations.RemoveField(
            model_name='smilesprite',
            name='dhash',
        ),
        migrations.RemoveField(
            model_name='smilesprite',
            name='main_color',
        ),
        migrations.RemoveField(
            model_name='smilesprite',
            name='size',
        ),
    ]
