# Generated by Django 3.2.7 on 2021-11-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maptroid', '0013_auto_20211127_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='world',
            name='hidden',
            field=models.BooleanField(default=True),
        ),
    ]
