# Generated by Django 3.2.7 on 2021-11-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maptroid', '0014_world_hidden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='world',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
