# Generated by Django 3.2.7 on 2021-12-01 14:56

from django.db import migrations, models
import unrest_image


class Migration(migrations.Migration):

    dependencies = [
        ('maptroid', '0015_alter_world_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='world',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='room',
            name='data',
            field=models.JSONField(blank=True, default=dict, encoder=unrest_image.NpEncoder),
        ),
    ]
