# Generated by Django 3.2.7 on 2021-12-04 00:50

from django.db import migrations, models
import maptroid.models


class Migration(migrations.Migration):

    dependencies = [
        ('maptroid', '0016_auto_20211201_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='data',
            field=models.JSONField(blank=True, default=maptroid.models.default_video_data),
        ),
    ]
