# Generated by Django 3.2.7 on 2021-12-12 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import maptroid.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maptroid', '0018_room_smile_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(blank=True, default=maptroid.models.default_video_data)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maptroid.world')),
            ],
        ),
    ]
