# Generated by Django 3.2.7 on 2022-03-06 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maptroid', '0020_auto_20220301_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smilesprite',
            name='template',
        ),
        migrations.AlterField(
            model_name='smilesprite',
            name='modifier',
            field=models.CharField(blank=True, choices=[('composite', 'composite'), ('inblock', 'inblock'), ('inegg', 'inegg'), ('respawn', 'respawn')], max_length=16, null=True),
        ),
    ]
