# Generated by Django 3.2.7 on 2022-03-29 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maptroid', '0021_auto_20220306_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='smilesprite',
            name='template',
            field=models.BooleanField(default=False),
        ),
    ]
